export const options = [
  { value: 1, label: "Manufacturing" },
  { value: 2, label: "Service" },
  { value: 3, label: "Other" },
  { value: 5, label: "Printing" },
  { value: 6, label: "Food and Beverage" },
  { value: 7, label: "Textile and Clothing" },
  { value: 8, label: "Wood" },
  { value: 9, label: "Plastic and Rubber" },
  { value: 11, label: "Metalworking" },
  { value: 12, label: "Machinery" },
  { value: 13, label: "Furniture" },
  { value: 18, label: "Electronics and Optics" },
  { value: 19, label: "Construction materials" },
  { value: 21, label: "Transport and Logistics" },
  { value: 22, label: "Tourism" },
  { value: 25, label: "Business services" },
  { value: 28, label: "Information Technology and Telecommunications" },
  { value: 29, label: "Energy technology" },
  { value: 33, label: "Environment" },
  { value: 35, label: "Engineering" },
  { value: 37, label: "Creative industries" },
  { value: 39, label: "Milk & dairy products" },
  { value: 40, label: "Meat & meat products" },
  { value: 42, label: "Fish & fish products" },
  { value: 43, label: "Beverages" },
  { value: 44, label: "Clothing" },
  { value: 45, label: "Textile" },
  { value: 47, label: "Wooden houses" },
  { value: 51, label: "Wooden building materials" },
  { value: 53, label: "Plastics welding and processing" },
  { value: 54, label: "Packaging" },
  { value: 55, label: "Blowing" },
  { value: 56, label: "Moulding" },
  { value: 57, label: "Moulding" },
  { value: 62, label: "Forgings, Fasteners" },
  { value: 66, label: "MIG, TIG, Aluminum welding" },
  { value: 67, label: "Construction of metal structures" },
  { value: 69, label: "Gas, Plasma, Laser cutting" },
  { value: 75, label: "CNC-machining" },
  { value: 93, label: "Metal structures" },
  { value: 94, label: "Machinery components" },
  { value: 97, label: "Maritime" },
  { value: 98, label: "Kitchen" },
  { value: 99, label: "Project furniture" },
  { value: 101, label: "Living room" },
  { value: 111, label: "Air" },
  { value: 112, label: "Road" },
  { value: 113, label: "Water" },
  { value: 114, label: "Rail" },
  { value: 121, label: "Software, Hardware" },
  { value: 122, label: "Telecommunications" },
  { value: 145, label: "Labelling and packaging printing" },
  { value: 148, label: "Advertising" },
  { value: 150, label: "Book/Periodicals printing" },
  { value: 141, label: "Translation services" },
  { value: 224, label: "Manufacture of machinery" },
  { value: 227, label: "Repair and maintenance service" },
  { value: 230, label: "Ship repair and conversion" },
  { value: 263, label: "Houses and buildings" },
  { value: 267, label: "Metal products" },
  { value: 269, label: "Boat/Yacht building" },
  { value: 271, label: "Aluminum and steel workboat" },
  { value: 337, label: "Other (Wood)" },
  { value: 341, label: "Outdoor" },
  { value: 385, label: "Bedroom" },
  { value: 389, label: "Bathroom/sauna" },
  { value: 390, label: "Children’s room" },
  { value: 392, label: "Office" },
  { value: 394, label: "Other (Furniture)" },
  { value: 508, label: "Other" },
  { value: 542, label: "Metal works" },
  { value: 556, label: "Plastic goods" },
  { value: 559, label: "Plastic processing technology" },
  { value: 560, label: "Plastic profiles" },
  { value: 576, label: "Programming, Consultancy" },
  { value: 581, label: "Data processing, Web portals, E-marketing" },
];
